//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo
    {
        public int todo_id { get; set; }
        public string descpt { get; set; }
        public Nullable<int> st_cd { get; set; }
        public Nullable<System.DateTime> crt_dt { get; set; }
    
        public virtual todo_sts todo_sts { get; set; }
    }
}
